SELECT a.PRODUCT_ID, a.PRODUCT_NAME, SUM(a.PRICE * b.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT a
    LEFT JOIN FOOD_ORDER b
    ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE MONTH(b.PRODUCE_DATE) = 5 AND YEAR(b.PRODUCE_DATE) = 2022
GROUP BY a.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, a.PRODUCT_ID ASC