SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F JOIN (SELECT CATEGORY, MAX(PRICE) AS PRICE FROM FOOD_PRODUCT GROUP BY CATEGORY) J ON F.CATEGORY = J.CATEGORY
WHERE (F.CATEGORY = '과자' OR F.CATEGORY = '국' OR F.CATEGORY = '김치' OR F.CATEGORY = '식용유')
AND F.PRICE = J.PRICE
GROUP BY F.CATEGORY
ORDER BY F.PRICE DESC;