SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM PATIENT p, DOCTOR d, APPOINTMENT a
WHERE p.PT_NO = a.PT_NO AND d.DR_ID = a.MDDR_ID
AND YEAR(a.APNT_YMD) = 2022 AND MONTH(a.APNT_YMD) = 4 AND DAY(a.APNT_YMD) = 13
AND a.APNT_CNCL_YN like "N"
ORDER BY a.APNT_YMD ASC